### ISSUE TITLE
Entity Framework

### ISSUE THREAD

**Issue by cassie113nl** [danielsen/DmarcRua#1]
Hi,

Is it possible to store the Feedback class via entity framework core?

Kind regards,

Casper

**Comment by danielsen** [comment]
No, it's not directly compatible. The Feedback class and it's related classes only have a transient relationship to each other as the output of the parser. 

Other users who have wanted to persist the reports to a database have written converters to cast the parser output classes to classes with defined relationships. The simplest way would be to convert each output class to a class which references it's parent classes via unique ids.
